export enum url {
  LANDING_PAGE = "/",
  LOGIN = "/login",
  FORGOT_PASSWORD = "/forgot-password",
  RESET_PASSWORD = "/reset-password",
  REGISTER = "/register",
  VERIFY_EMAIL = "/verify-email",
  INSTRUCTIONS = "/how-to",
  OVERVIEW = "/dashboard/overview",
  TRAFFIC = "/dashboard/e-traffic",
  POLICE = "/dashboard/e-police",
  MANAGEMENT = "/dashboard/management",
  FIRESERVICE = "/dashboard/fire-service",
  MEDICAL = "/dashboard/e-medical",
  PAGE404 = "",
}
