export enum url {
  LANDING_PAGE = "/",
  LOGIN = "/login",
  FORGOT_PASSWORD = "/forgot-password",
  RESET_PASSWORD = "/reset-password",
  REGISTER = "/register",
  VERIFY_EMAIL = "/verify-email",
  INSTRUCTIONS = "/how-to",
  OVERVIEW = "/dashboard/overview",
  TRAFFIC = "/dashboard/e-traffic",
  POLICE = "/dashboard/e-police",
  MANAGEMENT = "/dashboard/management",
  FIRESERVICE = "/dashboard/fire-service",
  PAGE404 = "",
}

export enum pageName {
  OVERVIEW = "Overview",
  APPLICATIONS = "Applications",
  CREATE_APP = "Create Application",
  USERS = "User Management",
  PROFILE = "Profile",
  ORGANIZATION = "Organization",
  BILLING = "Billing",
  API_BUNDLES = "API Bundles",
  API_CONFIGS = "API Configurations",
  API_CONFIG_GROUPS = "API Configuration Groups",
  SUBSCRIPTIONS = "Subscription",
  CLIENT_SUBSCRIPTIONS = "Client Subscriptions",
  API_DOCUMENTATION = "Documentation",
  PERMISSIONS = "Permissions",
  ROLES = "Roles",
}
