interface ICountryCode {
    continent_name: string;
    country_code: string;
    country_name: string;
    continent_code: string;
    capital_name: string;
    currency_code: string;
    phone_code: string;
    three_letter_country_code: string;
    image?: string;
}

export const CountryCodes: Array<ICountryCode> = [
    {
      "continent_name": "Europe",
      "country_code": "AD",
      "country_name": "Andorra",
      "continent_code": "EU",
      "capital_name": "Andorra la Vella",
      "currency_code": "EUR",
      "phone_code": "+376",
      "three_letter_country_code": "AND",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AD.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "AE",
      "country_name": "United Arab Emirates",
      "continent_code": "AS",
      "capital_name": "Abu Dhabi",
      "currency_code": "AED",
      "phone_code": "+971",
      "three_letter_country_code": "ARE",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AE.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "AF",
      "country_name": "Afghanistan",
      "continent_code": "AS",
      "capital_name": "Kabul",
      "currency_code": "AFN",
      "phone_code": "+93",
      "three_letter_country_code": "AFG",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AF.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "AG",
      "country_name": "Antigua and Barbuda",
      "continent_code": "NA",
      "capital_name": "St. John's",
      "currency_code": "XCD",
      "phone_code": "+1-268",
      "three_letter_country_code": "ATG",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AG.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "AI",
      "country_name": "Anguilla",
      "continent_code": "NA",
      "capital_name": "The Valley",
      "currency_code": "XCD",
      "phone_code": "+1-264",
      "three_letter_country_code": "AIA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AI.svg",
    },
    {
      "continent_name": "Europe",
      "country_code": "AL",
      "country_name": "Albania",
      "continent_code": "EU",
      "capital_name": "Tirana",
      "currency_code": "ALL",
      "phone_code": "+355",
      "three_letter_country_code": "ALB",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AL.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "AM",
      "country_name": "Armenia",
      "continent_code": "AS",
      "capital_name": "Yerevan",
      "currency_code": "AMD",
      "phone_code": "+374",
      "three_letter_country_code": "ARM",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AM.svg",
    },
    {
      "continent_name": "Africa",
      "country_code": "AO",
      "country_name": "Angola",
      "continent_code": "AF",
      "capital_name": "Luanda",
      "currency_code": "AOA",
      "phone_code": "+244",
      "three_letter_country_code": "AGO",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AO.svg",
    },
    {
      "continent_name": "Antarctica",
      "country_code": "AQ",
      "country_name": "Antarctica",
      "continent_code": "AN",
      "capital_name": "",
      "currency_code": "",
      "phone_code": "+",
      "three_letter_country_code": "ATA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AQ.svg"
    },
    {
      "continent_name": "South America",
      "country_code": "AR",
      "country_name": "Argentina",
      "continent_code": "SA",
      "capital_name": "Buenos Aires",
      "currency_code": "ARS",
      "phone_code": "+54",
      "three_letter_country_code": "ARG",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AR.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "AS",
      "country_name": "American Samoa",
      "continent_code": "OC",
      "capital_name": "Pago Pago",
      "currency_code": "USD",
      "phone_code": "+1-684",
      "three_letter_country_code": "ASM",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AS.svg",
    },
    {
      "continent_name": "Europe",
      "country_code": "AT",
      "country_name": "Austria",
      "continent_code": "EU",
      "capital_name": "Vienna",
      "currency_code": "EUR",
      "phone_code": "+43",
      "three_letter_country_code": "AUT",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AT.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "AU",
      "country_name": "Australia",
      "continent_code": "OC",
      "capital_name": "Canberra",
      "currency_code": "AUD",
      "phone_code": "+61",
      "three_letter_country_code": "AUS",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AU.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "AW",
      "country_name": "Aruba",
      "continent_code": "NA",
      "capital_name": "Oranjestad",
      "currency_code": "AWG",
      "phone_code": "+297",
      "three_letter_country_code": "ABW",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AW.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "AX",
      "country_name": "Aland Islands",
      "continent_code": "EU",
      "capital_name": "Mariehamn",
      "currency_code": "EUR",
      "phone_code": "+358-18",
      "three_letter_country_code": "ALA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AX.svg",

    },
    {
      "continent_name": "Asia",
      "country_code": "AZ",
      "country_name": "Azerbaijan",
      "continent_code": "AS",
      "capital_name": "Baku",
      "currency_code": "AZN",
      "phone_code": "+994",
      "three_letter_country_code": "AZE",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AZ.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "BA",
      "country_name": "Bosnia and Herzegovina",
      "continent_code": "EU",
      "capital_name": "Sarajevo",
      "currency_code": "BAM",
      "phone_code": "+387",
      "three_letter_country_code": "BIH",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BA.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "BB",
      "country_name": "Barbados",
      "continent_code": "NA",
      "capital_name": "Bridgetown",
      "currency_code": "BBD",
      "phone_code": "+1-246",
      "three_letter_country_code": "BRB",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BB.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "BD",
      "country_name": "Bangladesh",
      "continent_code": "AS",
      "capital_name": "Dhaka",
      "currency_code": "BDT",
      "phone_code": "+880",
      "three_letter_country_code": "BGD",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BD.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "BE",
      "country_name": "Belgium",
      "continent_code": "EU",
      "capital_name": "Brussels",
      "currency_code": "EUR",
      "phone_code": "+32",
      "three_letter_country_code": "BEL",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BE.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "BF",
      "country_name": "Burkina Faso",
      "continent_code": "AF",
      "capital_name": "Ouagadougou",
      "currency_code": "XOF",
      "phone_code": "+226",
      "three_letter_country_code": "BFA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BF.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "BG",
      "country_name": "Bulgaria",
      "continent_code": "EU",
      "capital_name": "Sofia",
      "currency_code": "BGN",
      "phone_code": "+359",
      "three_letter_country_code": "BGR",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BG.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "BH",
      "country_name": "Bahrain",
      "continent_code": "AS",
      "capital_name": "Manama",
      "currency_code": "BHD",
      "phone_code": "+973",
      "three_letter_country_code": "BHR",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BH.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "BI",
      "country_name": "Burundi",
      "continent_code": "AF",
      "capital_name": "Bujumbura",
      "currency_code": "BIF",
      "phone_code": "+257",
      "three_letter_country_code": "BDI",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BI.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "BJ",
      "country_name": "Benin",
      "continent_code": "AF",
      "capital_name": "Porto-Novo",
      "currency_code": "XOF",
      "phone_code": "+229",
      "three_letter_country_code": "BEN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BJ.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "BL",
      "country_name": "Saint Barthelemy",
      "continent_code": "NA",
      "capital_name": "Gustavia",
      "currency_code": "EUR",
      "phone_code": "+590",
      "three_letter_country_code": "BLM",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BL.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "BM",
      "country_name": "Bermuda",
      "continent_code": "NA",
      "capital_name": "Hamilton",
      "currency_code": "BMD",
      "phone_code": "+1-441",
      "three_letter_country_code": "BMU",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BM.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "BN",
      "country_name": "Brunei",
      "continent_code": "AS",
      "capital_name": "Bandar Seri Begawan",
      "currency_code": "BND",
      "phone_code": "+673",
      "three_letter_country_code": "BRN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BN.svg"
    },
    {
      "continent_name": "South America",
      "country_code": "BO",
      "country_name": "Bolivia",
      "continent_code": "SA",
      "capital_name": "Sucre",
      "currency_code": "BOB",
      "phone_code": "+591",
      "three_letter_country_code": "BOL",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BO.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "BQ",
      "country_name": "Bonaire, Saint Eustatius and Saba ",
      "continent_code": "NA",
      "capital_name": "",
      "currency_code": "USD",
      "phone_code": "+599",
      "three_letter_country_code": "BES",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BQ.svg"
    },
    {
      "continent_name": "South America",
      "country_code": "BR",
      "country_name": "Brazil",
      "continent_code": "SA",
      "capital_name": "Brasilia",
      "currency_code": "BRL",
      "phone_code": "+55",
      "three_letter_country_code": "BRA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BR.svg",
    },
    {
      "continent_name": "North America",
      "country_code": "BS",
      "country_name": "Bahamas",
      "continent_code": "NA",
      "capital_name": "Nassau",
      "currency_code": "BSD",
      "phone_code": "+1-242",
      "three_letter_country_code": "BHS",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BS.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "BT",
      "country_name": "Bhutan",
      "continent_code": "AS",
      "capital_name": "Thimphu",
      "currency_code": "BTN",
      "phone_code": "+975",
      "three_letter_country_code": "BTN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BT.svg"
    },
    {
      "continent_name": "Antarctica",
      "country_code": "BV",
      "country_name": "Bouvet Island",
      "continent_code": "AN",
      "capital_name": "",
      "currency_code": "NOK",
      "phone_code": "+",
      "three_letter_country_code": "BVT",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BV.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "BW",
      "country_name": "Botswana",
      "continent_code": "AF",
      "capital_name": "Gaborone",
      "currency_code": "BWP",
      "phone_code": "+267",
      "three_letter_country_code": "BWA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BW.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "BY",
      "country_name": "Belarus",
      "continent_code": "EU",
      "capital_name": "Minsk",
      "currency_code": "BYR",
      "phone_code": "+375",
      "three_letter_country_code": "BLR",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BY.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "BZ",
      "country_name": "Belize",
      "continent_code": "NA",
      "capital_name": "Belmopan",
      "currency_code": "BZD",
      "phone_code": "+501",
      "three_letter_country_code": "BLZ",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BZ.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "CA",
      "country_name": "Canada",
      "continent_code": "NA",
      "capital_name": "Ottawa",
      "currency_code": "CAD",
      "phone_code": "+1",
      "three_letter_country_code": "CAN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CA.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "CC",
      "country_name": "Cocos Islands",
      "continent_code": "AS",
      "capital_name": "West Island",
      "currency_code": "AUD",
      "phone_code": "+61",
      "three_letter_country_code": "CCK",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CC.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "CD",
      "country_name": "Democratic Republic of the Congo",
      "continent_code": "AF",
      "capital_name": "Kinshasa",
      "currency_code": "CDF",
      "phone_code": "+243",
      "three_letter_country_code": "COD",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CD.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "CF",
      "country_name": "Central African Republic",
      "continent_code": "AF",
      "capital_name": "Bangui",
      "currency_code": "XAF",
      "phone_code": "+236",
      "three_letter_country_code": "CAF",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CF.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "CG",
      "country_name": "Republic of the Congo",
      "continent_code": "AF",
      "capital_name": "Brazzaville",
      "currency_code": "XAF",
      "phone_code": "+242",
      "three_letter_country_code": "COG",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CG.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "CH",
      "country_name": "Switzerland",
      "continent_code": "EU",
      "capital_name": "Berne",
      "currency_code": "CHF",
      "phone_code": "+41",
      "three_letter_country_code": "CHE",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CH.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "CI",
      "country_name": "Ivory Coast",
      "continent_code": "AF",
      "capital_name": "Yamoussoukro",
      "currency_code": "XOF",
      "phone_code": "+225",
      "three_letter_country_code": "CIV",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CI.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "CK",
      "country_name": "Cook Islands",
      "continent_code": "OC",
      "capital_name": "Avarua",
      "currency_code": "NZD",
      "phone_code": "+682",
      "three_letter_country_code": "COK",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CK.svg"
    },
    {
      "continent_name": "South America",
      "country_code": "CL",
      "country_name": "Chile",
      "continent_code": "SA",
      "capital_name": "Santiago",
      "currency_code": "CLP",
      "phone_code": "+56",
      "three_letter_country_code": "CHL",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CL.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "CM",
      "country_name": "Cameroon",
      "continent_code": "AF",
      "capital_name": "Yaounde",
      "currency_code": "XAF",
      "phone_code": "+237",
      "three_letter_country_code": "CMR",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CM.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "CN",
      "country_name": "China",
      "continent_code": "AS",
      "capital_name": "Beijing",
      "currency_code": "CNY",
      "phone_code": "+86",
      "three_letter_country_code": "CHN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CN.svg"
    },
    {
      "continent_name": "South America",
      "country_code": "CO",
      "country_name": "Colombia",
      "continent_code": "SA",
      "capital_name": "Bogota",
      "currency_code": "COP",
      "phone_code": "+57",
      "three_letter_country_code": "COL",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CO.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "CR",
      "country_name": "Costa Rica",
      "continent_code": "NA",
      "capital_name": "San Jose",
      "currency_code": "CRC",
      "phone_code": "+506",
      "three_letter_country_code": "CRI",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CR.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "CU",
      "country_name": "Cuba",
      "continent_code": "NA",
      "capital_name": "Havana",
      "currency_code": "CUP",
      "phone_code": "+53",
      "three_letter_country_code": "CUB",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CU.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "CV",
      "country_name": "Cape Verde",
      "continent_code": "AF",
      "capital_name": "Praia",
      "currency_code": "CVE",
      "phone_code": "+238",
      "three_letter_country_code": "CPV",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CV.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "CW",
      "country_name": "Curacao",
      "continent_code": "NA",
      "capital_name": " Willemstad",
      "currency_code": "ANG",
      "phone_code": "+599",
      "three_letter_country_code": "CUW",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CW.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "CX",
      "country_name": "Christmas Island",
      "continent_code": "AS",
      "capital_name": "Flying Fish Cove",
      "currency_code": "AUD",
      "phone_code": "+61",
      "three_letter_country_code": "CXR",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CX.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "CY",
      "country_name": "Cyprus",
      "continent_code": "EU",
      "capital_name": "Nicosia",
      "currency_code": "EUR",
      "phone_code": "+357",
      "three_letter_country_code": "CYP",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CY.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "CZ",
      "country_name": "Czech Republic",
      "continent_code": "EU",
      "capital_name": "Prague",
      "currency_code": "CZK",
      "phone_code": "+420",
      "three_letter_country_code": "CZE",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CZ.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "DE",
      "country_name": "Germany",
      "continent_code": "EU",
      "capital_name": "Berlin",
      "currency_code": "EUR",
      "phone_code": "+49",
      "three_letter_country_code": "DEU",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DE.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "DJ",
      "country_name": "Djibouti",
      "continent_code": "AF",
      "capital_name": "Djibouti",
      "currency_code": "DJF",
      "phone_code": "+253",
      "three_letter_country_code": "DJI",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DJ.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "DK",
      "country_name": "Denmark",
      "continent_code": "EU",
      "capital_name": "Copenhagen",
      "currency_code": "DKK",
      "phone_code": "+45",
      "three_letter_country_code": "DNK",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DK.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "DM",
      "country_name": "Dominica",
      "continent_code": "NA",
      "capital_name": "Roseau",
      "currency_code": "XCD",
      "phone_code": "+1-767",
      "three_letter_country_code": "DMA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DM.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "DO",
      "country_name": "Dominican Republic",
      "continent_code": "NA",
      "capital_name": "Santo Domingo",
      "currency_code": "DOP",
      "phone_code": "+1-809 and 1-829",
      "three_letter_country_code": "DOM",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DO.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "DZ",
      "country_name": "Algeria",
      "continent_code": "AF",
      "capital_name": "Algiers",
      "currency_code": "DZD",
      "phone_code": "+213",
      "three_letter_country_code": "DZA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/Dz.svg"
    },
    {
      "continent_name": "South America",
      "country_code": "EC",
      "country_name": "Ecuador",
      "continent_code": "SA",
      "capital_name": "Quito",
      "currency_code": "USD",
      "phone_code": "+593",
      "three_letter_country_code": "ECU",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EC.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "EE",
      "country_name": "Estonia",
      "continent_code": "EU",
      "capital_name": "Tallinn",
      "currency_code": "EUR",
      "phone_code": "+372",
      "three_letter_country_code": "EST",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EE.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "EG",
      "country_name": "Egypt",
      "continent_code": "AF",
      "capital_name": "Cairo",
      "currency_code": "EGP",
      "phone_code": "+20",
      "three_letter_country_code": "EGY",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EG.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "EH",
      "country_name": "Western Sahara",
      "continent_code": "AF",
      "capital_name": "El-Aaiun",
      "currency_code": "MAD",
      "phone_code": "+212",
      "three_letter_country_code": "ESH",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EH.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "ER",
      "country_name": "Eritrea",
      "continent_code": "AF",
      "capital_name": "Asmara",
      "currency_code": "ERN",
      "phone_code": "+291",
      "three_letter_country_code": "ERI",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ER.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "ES",
      "country_name": "Spain",
      "continent_code": "EU",
      "capital_name": "Madrid",
      "currency_code": "EUR",
      "phone_code": "+34",
      "three_letter_country_code": "ESP",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ES.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "ET",
      "country_name": "Ethiopia",
      "continent_code": "AF",
      "capital_name": "Addis Ababa",
      "currency_code": "ETB",
      "phone_code": "+251",
      "three_letter_country_code": "ETH",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ET.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "FI",
      "country_name": "Finland",
      "continent_code": "EU",
      "capital_name": "Helsinki",
      "currency_code": "EUR",
      "phone_code": "+358",
      "three_letter_country_code": "FIN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FI.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "FJ",
      "country_name": "Fiji",
      "continent_code": "OC",
      "capital_name": "Suva",
      "currency_code": "FJD",
      "phone_code": "+679",
      "three_letter_country_code": "FJI",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FJ.svg"
    },
    {
      "continent_name": "South America",
      "country_code": "FK",
      "country_name": "Falkland Islands",
      "continent_code": "SA",
      "capital_name": "Stanley",
      "currency_code": "FKP",
      "phone_code": "+500",
      "three_letter_country_code": "FLK",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FK.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "FM",
      "country_name": "Micronesia",
      "continent_code": "OC",
      "capital_name": "Palikir",
      "currency_code": "USD",
      "phone_code": "+691",
      "three_letter_country_code": "FSM",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FM.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "FO",
      "country_name": "Faroe Islands",
      "continent_code": "EU",
      "capital_name": "Torshavn",
      "currency_code": "DKK",
      "phone_code": "+298",
      "three_letter_country_code": "FRO",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FO.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "FR",
      "country_name": "France",
      "continent_code": "EU",
      "capital_name": "Paris",
      "currency_code": "EUR",
      "phone_code": "+33",
      "three_letter_country_code": "FRA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FR.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "GA",
      "country_name": "Gabon",
      "continent_code": "AF",
      "capital_name": "Libreville",
      "currency_code": "XAF",
      "phone_code": "+241",
      "three_letter_country_code": "GAB",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GA.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "GB",
      "country_name": "United Kingdom",
      "continent_code": "EU",
      "capital_name": "London",
      "currency_code": "GBP",
      "phone_code": "+44",
      "three_letter_country_code": "GBR",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GB.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "GD",
      "country_name": "Grenada",
      "continent_code": "NA",
      "capital_name": "St. George's",
      "currency_code": "XCD",
      "phone_code": "+1-473",
      "three_letter_country_code": "GRD",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GD.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "GE",
      "country_name": "Georgia",
      "continent_code": "AS",
      "capital_name": "Tbilisi",
      "currency_code": "GEL",
      "phone_code": "+995",
      "three_letter_country_code": "GEO",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GE.svg"
    },
    {
      "continent_name": "South America",
      "country_code": "GF",
      "country_name": "French Guiana",
      "continent_code": "SA",
      "capital_name": "Cayenne",
      "currency_code": "EUR",
      "phone_code": "+594",
      "three_letter_country_code": "GUF",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GF.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "GG",
      "country_name": "Guernsey",
      "continent_code": "EU",
      "capital_name": "St Peter Port",
      "currency_code": "GBP",
      "phone_code": "+44-1481",
      "three_letter_country_code": "GGY",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GG.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "GH",
      "country_name": "Ghana",
      "continent_code": "AF",
      "capital_name": "Accra",
      "currency_code": "GHS",
      "phone_code": "+233",
      "three_letter_country_code": "GHA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GH.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "GI",
      "country_name": "Gibraltar",
      "continent_code": "EU",
      "capital_name": "Gibraltar",
      "currency_code": "GIP",
      "phone_code": "+350",
      "three_letter_country_code": "GIB",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GI.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "GL",
      "country_name": "Greenland",
      "continent_code": "NA",
      "capital_name": "Nuuk",
      "currency_code": "DKK",
      "phone_code": "+299",
      "three_letter_country_code": "GRL",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GL.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "GM",
      "country_name": "Gambia",
      "continent_code": "AF",
      "capital_name": "Banjul",
      "currency_code": "GMD",
      "phone_code": "+220",
      "three_letter_country_code": "GMB",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GM.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "GN",
      "country_name": "Guinea",
      "continent_code": "AF",
      "capital_name": "Conakry",
      "currency_code": "GNF",
      "phone_code": "+224",
      "three_letter_country_code": "GIN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GN.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "GP",
      "country_name": "Guadeloupe",
      "continent_code": "NA",
      "capital_name": "Basse-Terre",
      "currency_code": "EUR",
      "phone_code": "+590",
      "three_letter_country_code": "GLP",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GP.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "GQ",
      "country_name": "Equatorial Guinea",
      "continent_code": "AF",
      "capital_name": "Malabo",
      "currency_code": "XAF",
      "phone_code": "+240",
      "three_letter_country_code": "GNQ",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GQ.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "GR",
      "country_name": "Greece",
      "continent_code": "EU",
      "capital_name": "Athens",
      "currency_code": "EUR",
      "phone_code": "+30",
      "three_letter_country_code": "GRC",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GR.svg"
    },
    {
      "continent_name": "Antarctica",
      "country_code": "GS",
      "country_name": "South Georgia and the South Sandwich Islands",
      "continent_code": "AN",
      "capital_name": "Grytviken",
      "currency_code": "GBP",
      "phone_code": "+",
      "three_letter_country_code": "SGS",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GS.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "GT",
      "country_name": "Guatemala",
      "continent_code": "NA",
      "capital_name": "Guatemala City",
      "currency_code": "GTQ",
      "phone_code": "+502",
      "three_letter_country_code": "GTM",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GT.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "GU",
      "country_name": "Guam",
      "continent_code": "OC",
      "capital_name": "Hagatna",
      "currency_code": "USD",
      "phone_code": "+1-671",
      "three_letter_country_code": "GUM",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GU.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "GW",
      "country_name": "Guinea-Bissau",
      "continent_code": "AF",
      "capital_name": "Bissau",
      "currency_code": "XOF",
      "phone_code": "+245",
      "three_letter_country_code": "GNB",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GW.svg"
    },
    {
      "continent_name": "South America",
      "country_code": "GY",
      "country_name": "Guyana",
      "continent_code": "SA",
      "capital_name": "Georgetown",
      "currency_code": "GYD",
      "phone_code": "+592",
      "three_letter_country_code": "GUY",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GY.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "HK",
      "country_name": "Hong Kong",
      "continent_code": "AS",
      "capital_name": "Hong Kong",
      "currency_code": "HKD",
      "phone_code": "+852",
      "three_letter_country_code": "HKG",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HK.svg"
    },
    {
      "continent_name": "Antarctica",
      "country_code": "HM",
      "country_name": "Heard Island and McDonald Islands",
      "continent_code": "AN",
      "capital_name": "",
      "currency_code": "AUD",
      "phone_code": "+ ",
      "three_letter_country_code": "HMD",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HM.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "HN",
      "country_name": "Honduras",
      "continent_code": "NA",
      "capital_name": "Tegucigalpa",
      "currency_code": "HNL",
      "phone_code": "+504",
      "three_letter_country_code": "HND",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HN.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "HR",
      "country_name": "Croatia",
      "continent_code": "EU",
      "capital_name": "Zagreb",
      "currency_code": "HRK",
      "phone_code": "+385",
      "three_letter_country_code": "HRV",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HR.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "HT",
      "country_name": "Haiti",
      "continent_code": "NA",
      "capital_name": "Port-au-Prince",
      "currency_code": "HTG",
      "phone_code": "+509",
      "three_letter_country_code": "HTI",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HT.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "HU",
      "country_name": "Hungary",
      "continent_code": "EU",
      "capital_name": "Budapest",
      "currency_code": "HUF",
      "phone_code": "+36",
      "three_letter_country_code": "HUN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HU.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "ID",
      "country_name": "Indonesia",
      "continent_code": "AS",
      "capital_name": "Jakarta",
      "currency_code": "IDR",
      "phone_code": "+62",
      "three_letter_country_code": "IDN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ID.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "IE",
      "country_name": "Ireland",
      "continent_code": "EU",
      "capital_name": "Dublin",
      "currency_code": "EUR",
      "phone_code": "+353",
      "three_letter_country_code": "IRL",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IE.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "IL",
      "country_name": "Israel",
      "continent_code": "AS",
      "capital_name": "Jerusalem",
      "currency_code": "ILS",
      "phone_code": "+972",
      "three_letter_country_code": "ISR",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IL.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "IM",
      "country_name": "Isle of Man",
      "continent_code": "EU",
      "capital_name": "Douglas, Isle of Man",
      "currency_code": "GBP",
      "phone_code": "+44-1624",
      "three_letter_country_code": "IMN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IM.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "IN",
      "country_name": "India",
      "continent_code": "AS",
      "capital_name": "New Delhi",
      "currency_code": "INR",
      "phone_code": "+91",
      "three_letter_country_code": "IND",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IN.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "IO",
      "country_name": "British Indian Ocean Territory",
      "continent_code": "AS",
      "capital_name": "Diego Garcia",
      "currency_code": "USD",
      "phone_code": "+246",
      "three_letter_country_code": "IOT",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IO.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "IQ",
      "country_name": "Iraq",
      "continent_code": "AS",
      "capital_name": "Baghdad",
      "currency_code": "IQD",
      "phone_code": "+964",
      "three_letter_country_code": "IRQ",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IQ.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "IR",
      "country_name": "Iran",
      "continent_code": "AS",
      "capital_name": "Tehran",
      "currency_code": "IRR",
      "phone_code": "+98",
      "three_letter_country_code": "IRN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IR.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "IS",
      "country_name": "Iceland",
      "continent_code": "EU",
      "capital_name": "Reykjavik",
      "currency_code": "ISK",
      "phone_code": "+354",
      "three_letter_country_code": "ISL",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IS.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "IT",
      "country_name": "Italy",
      "continent_code": "EU",
      "capital_name": "Rome",
      "currency_code": "EUR",
      "phone_code": "+39",
      "three_letter_country_code": "ITA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IT.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "JE",
      "country_name": "Jersey",
      "continent_code": "EU",
      "capital_name": "Saint Helier",
      "currency_code": "GBP",
      "phone_code": "+44-1534",
      "three_letter_country_code": "JEY",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JE.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "JM",
      "country_name": "Jamaica",
      "continent_code": "NA",
      "capital_name": "Kingston",
      "currency_code": "JMD",
      "phone_code": "+1-876",
      "three_letter_country_code": "JAM",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JM.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "JO",
      "country_name": "Jordan",
      "continent_code": "AS",
      "capital_name": "Amman",
      "currency_code": "JOD",
      "phone_code": "+962",
      "three_letter_country_code": "JOR",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JO.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "JP",
      "country_name": "Japan",
      "continent_code": "AS",
      "capital_name": "Tokyo",
      "currency_code": "JPY",
      "phone_code": "+81",
      "three_letter_country_code": "JPN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JP.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "KE",
      "country_name": "Kenya",
      "continent_code": "AF",
      "capital_name": "Nairobi",
      "currency_code": "KES",
      "phone_code": "+254",
      "three_letter_country_code": "KEN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KE.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "KG",
      "country_name": "Kyrgyzstan",
      "continent_code": "AS",
      "capital_name": "Bishkek",
      "currency_code": "KGS",
      "phone_code": "+996",
      "three_letter_country_code": "KGZ",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KG.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "KH",
      "country_name": "Cambodia",
      "continent_code": "AS",
      "capital_name": "Phnom Penh",
      "currency_code": "KHR",
      "phone_code": "+855",
      "three_letter_country_code": "KHM",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KH.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "KI",
      "country_name": "Kiribati",
      "continent_code": "OC",
      "capital_name": "Tarawa",
      "currency_code": "AUD",
      "phone_code": "+686",
      "three_letter_country_code": "KIR",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KI.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "KM",
      "country_name": "Comoros",
      "continent_code": "AF",
      "capital_name": "Moroni",
      "currency_code": "KMF",
      "phone_code": "+269",
      "three_letter_country_code": "COM",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KM.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "KN",
      "country_name": "Saint Kitts and Nevis",
      "continent_code": "NA",
      "capital_name": "Basseterre",
      "currency_code": "XCD",
      "phone_code": "+1-869",
      "three_letter_country_code": "KNA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KN.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "KP",
      "country_name": "North Korea",
      "continent_code": "AS",
      "capital_name": "Pyongyang",
      "currency_code": "KPW",
      "phone_code": "+850",
      "three_letter_country_code": "PRK",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KP.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "KR",
      "country_name": "South Korea",
      "continent_code": "AS",
      "capital_name": "Seoul",
      "currency_code": "KRW",
      "phone_code": "+82",
      "three_letter_country_code": "KOR",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KR.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "KW",
      "country_name": "Kuwait",
      "continent_code": "AS",
      "capital_name": "Kuwait City",
      "currency_code": "KWD",
      "phone_code": "+965",
      "three_letter_country_code": "KWT",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KW.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "KY",
      "country_name": "Cayman Islands",
      "continent_code": "NA",
      "capital_name": "George Town",
      "currency_code": "KYD",
      "phone_code": "+1-345",
      "three_letter_country_code": "CYM",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KY.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "KZ",
      "country_name": "Kazakhstan",
      "continent_code": "AS",
      "capital_name": "Astana",
      "currency_code": "KZT",
      "phone_code": "+7",
      "three_letter_country_code": "KAZ",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KZ.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "LA",
      "country_name": "Laos",
      "continent_code": "AS",
      "capital_name": "Vientiane",
      "currency_code": "LAK",
      "phone_code": "+856",
      "three_letter_country_code": "LAO",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LA.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "LB",
      "country_name": "Lebanon",
      "continent_code": "AS",
      "capital_name": "Beirut",
      "currency_code": "LBP",
      "phone_code": "+961",
      "three_letter_country_code": "LBN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LB.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "LC",
      "country_name": "Saint Lucia",
      "continent_code": "NA",
      "capital_name": "Castries",
      "currency_code": "XCD",
      "phone_code": "+1-758",
      "three_letter_country_code": "LCA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LC.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "LI",
      "country_name": "Liechtenstein",
      "continent_code": "EU",
      "capital_name": "Vaduz",
      "currency_code": "CHF",
      "phone_code": "+423",
      "three_letter_country_code": "LIE",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LI.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "LK",
      "country_name": "Sri Lanka",
      "continent_code": "AS",
      "capital_name": "Colombo",
      "currency_code": "LKR",
      "phone_code": "+94",
      "three_letter_country_code": "LKA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LK.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "LR",
      "country_name": "Liberia",
      "continent_code": "AF",
      "capital_name": "Monrovia",
      "currency_code": "LRD",
      "phone_code": "+231",
      "three_letter_country_code": "LBR",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LR.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "LS",
      "country_name": "Lesotho",
      "continent_code": "AF",
      "capital_name": "Maseru",
      "currency_code": "LSL",
      "phone_code": "+266",
      "three_letter_country_code": "LSO",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LS.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "LT",
      "country_name": "Lithuania",
      "continent_code": "EU",
      "capital_name": "Vilnius",
      "currency_code": "LTL",
      "phone_code": "+370",
      "three_letter_country_code": "LTU",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LT.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "LU",
      "country_name": "Luxembourg",
      "continent_code": "EU",
      "capital_name": "Luxembourg",
      "currency_code": "EUR",
      "phone_code": "+352",
      "three_letter_country_code": "LUX",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LU.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "LV",
      "country_name": "Latvia",
      "continent_code": "EU",
      "capital_name": "Riga",
      "currency_code": "EUR",
      "phone_code": "+371",
      "three_letter_country_code": "LVA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LV.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "LY",
      "country_name": "Libya",
      "continent_code": "AF",
      "capital_name": "Tripolis",
      "currency_code": "LYD",
      "phone_code": "+218",
      "three_letter_country_code": "LBY",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LY.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "MA",
      "country_name": "Morocco",
      "continent_code": "AF",
      "capital_name": "Rabat",
      "currency_code": "MAD",
      "phone_code": "+212",
      "three_letter_country_code": "MAR",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MA.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "MC",
      "country_name": "Monaco",
      "continent_code": "EU",
      "capital_name": "Monaco",
      "currency_code": "EUR",
      "phone_code": "+377",
      "three_letter_country_code": "MCO",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MC.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "MD",
      "country_name": "Moldova",
      "continent_code": "EU",
      "capital_name": "Chisinau",
      "currency_code": "MDL",
      "phone_code": "+373",
      "three_letter_country_code": "MDA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MD.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "ME",
      "country_name": "Montenegro",
      "continent_code": "EU",
      "capital_name": "Podgorica",
      "currency_code": "EUR",
      "phone_code": "+382",
      "three_letter_country_code": "MNE",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ME.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "MF",
      "country_name": "Saint Martin",
      "continent_code": "NA",
      "capital_name": "Marigot",
      "currency_code": "EUR",
      "phone_code": "+590",
      "three_letter_country_code": "MAF",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MF.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "MG",
      "country_name": "Madagascar",
      "continent_code": "AF",
      "capital_name": "Antananarivo",
      "currency_code": "MGA",
      "phone_code": "+261",
      "three_letter_country_code": "MDG",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MG.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "MH",
      "country_name": "Marshall Islands",
      "continent_code": "OC",
      "capital_name": "Majuro",
      "currency_code": "USD",
      "phone_code": "+692",
      "three_letter_country_code": "MHL",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MH.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "MK",
      "country_name": "Macedonia",
      "continent_code": "EU",
      "capital_name": "Skopje",
      "currency_code": "MKD",
      "phone_code": "+389",
      "three_letter_country_code": "MKD",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MK.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "ML",
      "country_name": "Mali",
      "continent_code": "AF",
      "capital_name": "Bamako",
      "currency_code": "XOF",
      "phone_code": "+223",
      "three_letter_country_code": "MLI",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ML.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "MM",
      "country_name": "Myanmar",
      "continent_code": "AS",
      "capital_name": "Nay Pyi Taw",
      "currency_code": "MMK",
      "phone_code": "+95",
      "three_letter_country_code": "MMR",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MM.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "MN",
      "country_name": "Mongolia",
      "continent_code": "AS",
      "capital_name": "Ulan Bator",
      "currency_code": "MNT",
      "phone_code": "+976",
      "three_letter_country_code": "MNG",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MN.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "MO",
      "country_name": "Macao",
      "continent_code": "AS",
      "capital_name": "Macao",
      "currency_code": "MOP",
      "phone_code": "+853",
      "three_letter_country_code": "MAC",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MO.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "MP",
      "country_name": "Northern Mariana Islands",
      "continent_code": "OC",
      "capital_name": "Saipan",
      "currency_code": "USD",
      "phone_code": "+1-670",
      "three_letter_country_code": "MNP",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MP.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "MQ",
      "country_name": "Martinique",
      "continent_code": "NA",
      "capital_name": "Fort-de-France",
      "currency_code": "EUR",
      "phone_code": "+596",
      "three_letter_country_code": "MTQ",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MQ.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "MR",
      "country_name": "Mauritania",
      "continent_code": "AF",
      "capital_name": "Nouakchott",
      "currency_code": "MRO",
      "phone_code": "+222",
      "three_letter_country_code": "MRT",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MR.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "MS",
      "country_name": "Montserrat",
      "continent_code": "NA",
      "capital_name": "Plymouth",
      "currency_code": "XCD",
      "phone_code": "+1-664",
      "three_letter_country_code": "MSR",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MS.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "MT",
      "country_name": "Malta",
      "continent_code": "EU",
      "capital_name": "Valletta",
      "currency_code": "EUR",
      "phone_code": "+356",
      "three_letter_country_code": "MLT",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MT.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "MU",
      "country_name": "Mauritius",
      "continent_code": "AF",
      "capital_name": "Port Louis",
      "currency_code": "MUR",
      "phone_code": "+230",
      "three_letter_country_code": "MUS",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MU.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "MV",
      "country_name": "Maldives",
      "continent_code": "AS",
      "capital_name": "Male",
      "currency_code": "MVR",
      "phone_code": "+960",
      "three_letter_country_code": "MDV",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MV.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "MW",
      "country_name": "Malawi",
      "continent_code": "AF",
      "capital_name": "Lilongwe",
      "currency_code": "MWK",
      "phone_code": "+265",
      "three_letter_country_code": "MWI",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MW.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "MX",
      "country_name": "Mexico",
      "continent_code": "NA",
      "capital_name": "Mexico City",
      "currency_code": "MXN",
      "phone_code": "+52",
      "three_letter_country_code": "MEX",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MX.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "MY",
      "country_name": "Malaysia",
      "continent_code": "AS",
      "capital_name": "Kuala Lumpur",
      "currency_code": "MYR",
      "phone_code": "+60",
      "three_letter_country_code": "MYS",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MY.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "MZ",
      "country_name": "Mozambique",
      "continent_code": "AF",
      "capital_name": "Maputo",
      "currency_code": "MZN",
      "phone_code": "+258",
      "three_letter_country_code": "MOZ",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MZ.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "NA",
      "country_name": "Namibia",
      "continent_code": "AF",
      "capital_name": "Windhoek",
      "currency_code": "NAD",
      "phone_code": "+264",
      "three_letter_country_code": "NAM",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NA.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "NC",
      "country_name": "New Caledonia",
      "continent_code": "OC",
      "capital_name": "Noumea",
      "currency_code": "XPF",
      "phone_code": "+687",
      "three_letter_country_code": "NCL",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NC.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "NE",
      "country_name": "Niger",
      "continent_code": "AF",
      "capital_name": "Niamey",
      "currency_code": "XOF",
      "phone_code": "+227",
      "three_letter_country_code": "NER",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NE.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "NF",
      "country_name": "Norfolk Island",
      "continent_code": "OC",
      "capital_name": "Kingston",
      "currency_code": "AUD",
      "phone_code": "+672",
      "three_letter_country_code": "NFK",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NF.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "NG",
      "country_name": "Nigeria",
      "continent_code": "AF",
      "capital_name": "Abuja",
      "currency_code": "NGN",
      "phone_code": "+234",
      "three_letter_country_code": "NGA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NG.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "NI",
      "country_name": "Nicaragua",
      "continent_code": "NA",
      "capital_name": "Managua",
      "currency_code": "NIO",
      "phone_code": "+505",
      "three_letter_country_code": "NIC",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NI.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "NL",
      "country_name": "Netherlands",
      "continent_code": "EU",
      "capital_name": "Amsterdam",
      "currency_code": "EUR",
      "phone_code": "+31",
      "three_letter_country_code": "NLD",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NL.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "NO",
      "country_name": "Norway",
      "continent_code": "EU",
      "capital_name": "Oslo",
      "currency_code": "NOK",
      "phone_code": "+47",
      "three_letter_country_code": "NOR",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NO.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "NP",
      "country_name": "Nepal",
      "continent_code": "AS",
      "capital_name": "Kathmandu",
      "currency_code": "NPR",
      "phone_code": "+977",
      "three_letter_country_code": "NPL",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NP.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "NR",
      "country_name": "Nauru",
      "continent_code": "OC",
      "capital_name": "Yaren",
      "currency_code": "AUD",
      "phone_code": "+674",
      "three_letter_country_code": "NRU",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NR.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "NU",
      "country_name": "Niue",
      "continent_code": "OC",
      "capital_name": "Alofi",
      "currency_code": "NZD",
      "phone_code": "+683",
      "three_letter_country_code": "NIU",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NU.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "NZ",
      "country_name": "New Zealand",
      "continent_code": "OC",
      "capital_name": "Wellington",
      "currency_code": "NZD",
      "phone_code": "+64",
      "three_letter_country_code": "NZL",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NZ.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "OM",
      "country_name": "Oman",
      "continent_code": "AS",
      "capital_name": "Muscat",
      "currency_code": "OMR",
      "phone_code": "+968",
      "three_letter_country_code": "OMN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/OM.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "PA",
      "country_name": "Panama",
      "continent_code": "NA",
      "capital_name": "Panama City",
      "currency_code": "PAB",
      "phone_code": "+507",
      "three_letter_country_code": "PAN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PA.svg"
    },
    {
      "continent_name": "South America",
      "country_code": "PE",
      "country_name": "Peru",
      "continent_code": "SA",
      "capital_name": "Lima",
      "currency_code": "PEN",
      "phone_code": "+51",
      "three_letter_country_code": "PER",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PE.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "PF",
      "country_name": "French Polynesia",
      "continent_code": "OC",
      "capital_name": "Papeete",
      "currency_code": "XPF",
      "phone_code": "+689",
      "three_letter_country_code": "PYF",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PF.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "PG",
      "country_name": "Papua New Guinea",
      "continent_code": "OC",
      "capital_name": "Port Moresby",
      "currency_code": "PGK",
      "phone_code": "+675",
      "three_letter_country_code": "PNG",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PG.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "PH",
      "country_name": "Philippines",
      "continent_code": "AS",
      "capital_name": "Manila",
      "currency_code": "PHP",
      "phone_code": "+63",
      "three_letter_country_code": "PHL",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PH.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "PK",
      "country_name": "Pakistan",
      "continent_code": "AS",
      "capital_name": "Islamabad",
      "currency_code": "PKR",
      "phone_code": "+92",
      "three_letter_country_code": "PAK",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PK.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "PL",
      "country_name": "Poland",
      "continent_code": "EU",
      "capital_name": "Warsaw",
      "currency_code": "PLN",
      "phone_code": "+48",
      "three_letter_country_code": "POL",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PL.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "PM",
      "country_name": "Saint Pierre and Miquelon",
      "continent_code": "NA",
      "capital_name": "Saint-Pierre",
      "currency_code": "EUR",
      "phone_code": "+508",
      "three_letter_country_code": "SPM",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PM.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "PN",
      "country_name": "Pitcairn",
      "continent_code": "OC",
      "capital_name": "Adamstown",
      "currency_code": "NZD",
      "phone_code": "+870",
      "three_letter_country_code": "PCN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PN.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "PR",
      "country_name": "Puerto Rico",
      "continent_code": "NA",
      "capital_name": "San Juan",
      "currency_code": "USD",
      "phone_code": "+1-787 and 1-939",
      "three_letter_country_code": "PRI",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PR.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "PS",
      "country_name": "Palestinian Territory",
      "continent_code": "AS",
      "capital_name": "East Jerusalem",
      "currency_code": "ILS",
      "phone_code": "+970",
      "three_letter_country_code": "PSE",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PS.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "PT",
      "country_name": "Portugal",
      "continent_code": "EU",
      "capital_name": "Lisbon",
      "currency_code": "EUR",
      "phone_code": "+351",
      "three_letter_country_code": "PRT",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PT.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "PW",
      "country_name": "Palau",
      "continent_code": "OC",
      "capital_name": "Melekeok",
      "currency_code": "USD",
      "phone_code": "+680",
      "three_letter_country_code": "PLW",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PW.svg"
    },
    {
      "continent_name": "South America",
      "country_code": "PY",
      "country_name": "Paraguay",
      "continent_code": "SA",
      "capital_name": "Asuncion",
      "currency_code": "PYG",
      "phone_code": "+595",
      "three_letter_country_code": "PRY",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PY.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "QA",
      "country_name": "Qatar",
      "continent_code": "AS",
      "capital_name": "Doha",
      "currency_code": "QAR",
      "phone_code": "+974",
      "three_letter_country_code": "QAT",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/QA.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "RE",
      "country_name": "Reunion",
      "continent_code": "AF",
      "capital_name": "Saint-Denis",
      "currency_code": "EUR",
      "phone_code": "+262",
      "three_letter_country_code": "REU",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RE.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "RO",
      "country_name": "Romania",
      "continent_code": "EU",
      "capital_name": "Bucharest",
      "currency_code": "RON",
      "phone_code": "+40",
      "three_letter_country_code": "ROU",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RO.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "RS",
      "country_name": "Serbia",
      "continent_code": "EU",
      "capital_name": "Belgrade",
      "currency_code": "RSD",
      "phone_code": "+381",
      "three_letter_country_code": "SRB",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RS.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "RU",
      "country_name": "Russia",
      "continent_code": "EU",
      "capital_name": "Moscow",
      "currency_code": "RUB",
      "phone_code": "+7",
      "three_letter_country_code": "RUS",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RU.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "RW",
      "country_name": "Rwanda",
      "continent_code": "AF",
      "capital_name": "Kigali",
      "currency_code": "RWF",
      "phone_code": "+250",
      "three_letter_country_code": "RWA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RW.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "SA",
      "country_name": "Saudi Arabia",
      "continent_code": "AS",
      "capital_name": "Riyadh",
      "currency_code": "SAR",
      "phone_code": "+966",
      "three_letter_country_code": "SAU",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SA.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "SB",
      "country_name": "Solomon Islands",
      "continent_code": "OC",
      "capital_name": "Honiara",
      "currency_code": "SBD",
      "phone_code": "+677",
      "three_letter_country_code": "SLB",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SB.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "SC",
      "country_name": "Seychelles",
      "continent_code": "AF",
      "capital_name": "Victoria",
      "currency_code": "SCR",
      "phone_code": "+248",
      "three_letter_country_code": "SYC",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SC.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "SD",
      "country_name": "Sudan",
      "continent_code": "AF",
      "capital_name": "Khartoum",
      "currency_code": "SDG",
      "phone_code": "+249",
      "three_letter_country_code": "SDN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SD.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "SE",
      "country_name": "Sweden",
      "continent_code": "EU",
      "capital_name": "Stockholm",
      "currency_code": "SEK",
      "phone_code": "+46",
      "three_letter_country_code": "SWE",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SE.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "SG",
      "country_name": "Singapore",
      "continent_code": "AS",
      "capital_name": "Singapur",
      "currency_code": "SGD",
      "phone_code": "+65",
      "three_letter_country_code": "SGP",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SG.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "SH",
      "country_name": "Saint Helena",
      "continent_code": "AF",
      "capital_name": "Jamestown",
      "currency_code": "SHP",
      "phone_code": "+290",
      "three_letter_country_code": "SHN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SH.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "SI",
      "country_name": "Slovenia",
      "continent_code": "EU",
      "capital_name": "Ljubljana",
      "currency_code": "EUR",
      "phone_code": "+386",
      "three_letter_country_code": "SVN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SI.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "SJ",
      "country_name": "Svalbard and Jan Mayen",
      "continent_code": "EU",
      "capital_name": "Longyearbyen",
      "currency_code": "NOK",
      "phone_code": "+47",
      "three_letter_country_code": "SJM",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SJ.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "SK",
      "country_name": "Slovakia",
      "continent_code": "EU",
      "capital_name": "Bratislava",
      "currency_code": "EUR",
      "phone_code": "+421",
      "three_letter_country_code": "SVK",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SK.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "SL",
      "country_name": "Sierra Leone",
      "continent_code": "AF",
      "capital_name": "Freetown",
      "currency_code": "SLL",
      "phone_code": "+232",
      "three_letter_country_code": "SLE",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SL.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "SM",
      "country_name": "San Marino",
      "continent_code": "EU",
      "capital_name": "San Marino",
      "currency_code": "EUR",
      "phone_code": "+378",
      "three_letter_country_code": "SMR",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SM.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "SN",
      "country_name": "Senegal",
      "continent_code": "AF",
      "capital_name": "Dakar",
      "currency_code": "XOF",
      "phone_code": "+221",
      "three_letter_country_code": "SEN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SN.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "SO",
      "country_name": "Somalia",
      "continent_code": "AF",
      "capital_name": "Mogadishu",
      "currency_code": "SOS",
      "phone_code": "+252",
      "three_letter_country_code": "SOM",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SO.svg"
    },
    {
      "continent_name": "South America",
      "country_code": "SR",
      "country_name": "Suriname",
      "continent_code": "SA",
      "capital_name": "Paramaribo",
      "currency_code": "SRD",
      "phone_code": "+597",
      "three_letter_country_code": "SUR",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SR.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "SS",
      "country_name": "South Sudan",
      "continent_code": "AF",
      "capital_name": "Juba",
      "currency_code": "SSP",
      "phone_code": "+211",
      "three_letter_country_code": "SSD",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SS.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "ST",
      "country_name": "Sao Tome and Principe",
      "continent_code": "AF",
      "capital_name": "Sao Tome",
      "currency_code": "STD",
      "phone_code": "+239",
      "three_letter_country_code": "STP",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ST.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "SV",
      "country_name": "El Salvador",
      "continent_code": "NA",
      "capital_name": "San Salvador",
      "currency_code": "USD",
      "phone_code": "+503",
      "three_letter_country_code": "SLV",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SV.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "SX",
      "country_name": "Sint Maarten",
      "continent_code": "NA",
      "capital_name": "Philipsburg",
      "currency_code": "ANG",
      "phone_code": "+599",
      "three_letter_country_code": "SXM",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SX.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "SY",
      "country_name": "Syria",
      "continent_code": "AS",
      "capital_name": "Damascus",
      "currency_code": "SYP",
      "phone_code": "+963",
      "three_letter_country_code": "SYR",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SY.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "SZ",
      "country_name": "Swaziland",
      "continent_code": "AF",
      "capital_name": "Mbabane",
      "currency_code": "SZL",
      "phone_code": "+268",
      "three_letter_country_code": "SWZ",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SZ.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "TC",
      "country_name": "Turks and Caicos Islands",
      "continent_code": "NA",
      "capital_name": "Cockburn Town",
      "currency_code": "USD",
      "phone_code": "+1-649",
      "three_letter_country_code": "TCA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TC.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "TD",
      "country_name": "Chad",
      "continent_code": "AF",
      "capital_name": "N'Djamena",
      "currency_code": "XAF",
      "phone_code": "+235",
      "three_letter_country_code": "TCD",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TD.svg"
    },
    {
      "continent_name": "Antarctica",
      "country_code": "TF",
      "country_name": "French Southern Territories",
      "continent_code": "AN",
      "capital_name": "Port-aux-Francais",
      "currency_code": "EUR",
      "phone_code": "+",
      "three_letter_country_code": "ATF",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TF.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "TG",
      "country_name": "Togo",
      "continent_code": "AF",
      "capital_name": "Lome",
      "currency_code": "XOF",
      "phone_code": "+228",
      "three_letter_country_code": "TGO",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TG.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "TH",
      "country_name": "Thailand",
      "continent_code": "AS",
      "capital_name": "Bangkok",
      "currency_code": "THB",
      "phone_code": "+66",
      "three_letter_country_code": "THA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TH.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "TJ",
      "country_name": "Tajikistan",
      "continent_code": "AS",
      "capital_name": "Dushanbe",
      "currency_code": "TJS",
      "phone_code": "+992",
      "three_letter_country_code": "TJK",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TJ.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "TK",
      "country_name": "Tokelau",
      "continent_code": "OC",
      "capital_name": "",
      "currency_code": "NZD",
      "phone_code": "+690",
      "three_letter_country_code": "TKL",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TK.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "TL",
      "country_name": "East Timor",
      "continent_code": "OC",
      "capital_name": "Dili",
      "currency_code": "USD",
      "phone_code": "+670",
      "three_letter_country_code": "TLS",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TL.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "TM",
      "country_name": "Turkmenistan",
      "continent_code": "AS",
      "capital_name": "Ashgabat",
      "currency_code": "TMT",
      "phone_code": "+993",
      "three_letter_country_code": "TKM",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TM.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "TN",
      "country_name": "Tunisia",
      "continent_code": "AF",
      "capital_name": "Tunis",
      "currency_code": "TND",
      "phone_code": "+216",
      "three_letter_country_code": "TUN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TN.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "TO",
      "country_name": "Tonga",
      "continent_code": "OC",
      "capital_name": "Nuku'alofa",
      "currency_code": "TOP",
      "phone_code": "+676",
      "three_letter_country_code": "TON",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TO.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "TR",
      "country_name": "Turkey",
      "continent_code": "AS",
      "capital_name": "Ankara",
      "currency_code": "TRY",
      "phone_code": "+90",
      "three_letter_country_code": "TUR",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TR.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "TT",
      "country_name": "Trinidad and Tobago",
      "continent_code": "NA",
      "capital_name": "Port of Spain",
      "currency_code": "TTD",
      "phone_code": "+1-868",
      "three_letter_country_code": "TTO",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TT.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "TV",
      "country_name": "Tuvalu",
      "continent_code": "OC",
      "capital_name": "Funafuti",
      "currency_code": "AUD",
      "phone_code": "+688",
      "three_letter_country_code": "TUV",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TV.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "TW",
      "country_name": "Taiwan",
      "continent_code": "AS",
      "capital_name": "Taipei",
      "currency_code": "TWD",
      "phone_code": "+886",
      "three_letter_country_code": "TWN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TW.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "TZ",
      "country_name": "Tanzania",
      "continent_code": "AF",
      "capital_name": "Dodoma",
      "currency_code": "TZS",
      "phone_code": "+255",
      "three_letter_country_code": "TZA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TZ.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "UA",
      "country_name": "Ukraine",
      "continent_code": "EU",
      "capital_name": "Kiev",
      "currency_code": "UAH",
      "phone_code": "+380",
      "three_letter_country_code": "UKR",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UA.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "UG",
      "country_name": "Uganda",
      "continent_code": "AF",
      "capital_name": "Kampala",
      "currency_code": "UGX",
      "phone_code": "+256",
      "three_letter_country_code": "UGA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UG.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "UM",
      "country_name": "United States Minor Outlying Islands",
      "continent_code": "OC",
      "capital_name": "",
      "currency_code": "USD",
      "phone_code": "+1",
      "three_letter_country_code": "UMI",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UM.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "US",
      "country_name": "United States",
      "continent_code": "NA",
      "capital_name": "Washington",
      "currency_code": "USD",
      "phone_code": "+1",
      "three_letter_country_code": "USA",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/US.svg"
    },
    {
      "continent_name": "South America",
      "country_code": "UY",
      "country_name": "Uruguay",
      "continent_code": "SA",
      "capital_name": "Montevideo",
      "currency_code": "UYU",
      "phone_code": "+598",
      "three_letter_country_code": "URY",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UY.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "UZ",
      "country_name": "Uzbekistan",
      "continent_code": "AS",
      "capital_name": "Tashkent",
      "currency_code": "UZS",
      "phone_code": "+998",
      "three_letter_country_code": "UZB",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UZ.svg"
    },
    {
      "continent_name": "Europe",
      "country_code": "VA",
      "country_name": "Vatican",
      "continent_code": "EU",
      "capital_name": "Vatican City",
      "currency_code": "EUR",
      "phone_code": "+379",
      "three_letter_country_code": "VAT",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VA.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "VC",
      "country_name": "Saint Vincent and the Grenadines",
      "continent_code": "NA",
      "capital_name": "Kingstown",
      "currency_code": "XCD",
      "phone_code": "+1-784",
      "three_letter_country_code": "VCT",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VC.svg"
    },
    {
      "continent_name": "South America",
      "country_code": "VE",
      "country_name": "Venezuela",
      "continent_code": "SA",
      "capital_name": "Caracas",
      "currency_code": "VEF",
      "phone_code": "+58",
      "three_letter_country_code": "VEN",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VE.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "VG",
      "country_name": "British Virgin Islands",
      "continent_code": "NA",
      "capital_name": "Road Town",
      "currency_code": "USD",
      "phone_code": "+1-284",
      "three_letter_country_code": "VGB",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VG.svg"
    },
    {
      "continent_name": "North America",
      "country_code": "VI",
      "country_name": "U.S. Virgin Islands",
      "continent_code": "NA",
      "capital_name": "Charlotte Amalie",
      "currency_code": "USD",
      "phone_code": "+1-340",
      "three_letter_country_code": "VIR",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VI.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "VN",
      "country_name": "Vietnam",
      "continent_code": "AS",
      "capital_name": "Hanoi",
      "currency_code": "VND",
      "phone_code": "+84",
      "three_letter_country_code": "VNM",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VN.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "VU",
      "country_name": "Vanuatu",
      "continent_code": "OC",
      "capital_name": "Port Vila",
      "currency_code": "VUV",
      "phone_code": "+678",
      "three_letter_country_code": "VUT",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VU.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "WF",
      "country_name": "Wallis and Futuna",
      "continent_code": "OC",
      "capital_name": "Mata Utu",
      "currency_code": "XPF",
      "phone_code": "+681",
      "three_letter_country_code": "WLF",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WF.svg"
    },
    {
      "continent_name": "Oceania",
      "country_code": "WS",
      "country_name": "Samoa",
      "continent_code": "OC",
      "capital_name": "Apia",
      "currency_code": "WST",
      "phone_code": "+685",
      "three_letter_country_code": "WSM",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WS.svg"
    },
    {
      "country_code": "XK",
      "country_name": "Kosovo",
      "continent_code": "EU",
      "continent_name": "Europe",
      "capital_name": "Pristina",
      "currency_code": "EUR",
      "phone_code": "+",
      "three_letter_country_code": "KSV",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/XK.svg"
    },
    {
      "continent_name": "Asia",
      "country_code": "YE",
      "country_name": "Yemen",
      "continent_code": "AS",
      "capital_name": "Sanaa",
      "currency_code": "YER",
      "phone_code": "+967",
      "three_letter_country_code": "YEM",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/YE.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "YT",
      "country_name": "Mayotte",
      "continent_code": "AF",
      "capital_name": "Mamoudzou",
      "currency_code": "EUR",
      "phone_code": "+262",
      "three_letter_country_code": "MYT",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/YT.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "ZA",
      "country_name": "South Africa",
      "continent_code": "AF",
      "capital_name": "Pretoria",
      "currency_code": "ZAR",
      "phone_code": "+27",
      "three_letter_country_code": "ZAF",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZA.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "ZM",
      "country_name": "Zambia",
      "continent_code": "AF",
      "capital_name": "Lusaka",
      "currency_code": "ZMK",
      "phone_code": "+260",
      "three_letter_country_code": "ZMB",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZM.svg"
    },
    {
      "continent_name": "Africa",
      "country_code": "ZW",
      "country_name": "Zimbabwe",
      "continent_code": "AF",
      "capital_name": "Harare",
      "currency_code": "ZWL",
      "phone_code": "+263",
      "three_letter_country_code": "ZWE",
      image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZW.svg"
    }
]